### ISSUE TITLE
[Bug] Plugin isn't working

### ISSUE THREAD

**Issue by ImmortalZypther** [ngrst183/SuppressMentions#1]
The plugin appears to be broken because of an update in Discord, could this be fixed?

**Comment by ngrst183** [comment]
Hi, sorry lad, guess I didn't have this repo watched. 

Working on a fix now.

**Comment by ngrst183** [comment]
Weird, the plugin still works for me, but I've gotten reports from other people that the plugin doesn't work for them either. 

Any errors in the console?

**Comment by ImmortalZypther** [comment]
I see some errors that mention other plugins, but nothing that mentions this plugin specifically
If you made a version with a bunch of tests printing to the console, I could test that version for you

**Comment by ngrst183** [comment]
A friend of mine had a similar issue to yours, had him test a new version of the plugin for me. It seems to work for him, I changed the way its patched to be less destructive. 

Try it out and see if it works for you.

**Comment by ImmortalZypther** [comment]
It works now, thank you so much for the quick fix!
